# Generated by Django 5.0.1 on 2024-02-01 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_books_delete_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Main',
        ),
    ]
